Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.synced_folder "..", "/vagrant", :mount_options => ["dmode=777","fmode=777"]
  config.vm.network :forwarded_port, host: 9999, guest: 80
  config.vm.provision :shell,
  path: "drupal10.build.sh"
end
